#! /bin/sh

setxkbmap -option grp:alt_shift_toggle -option ctrl:nocaps -layout us,ru
xrandr --output HDMI1 --off --output eDP1 --auto --primary
xrandr --dpi 128
export CHROMIUM_USER_FLAGS="--force-device-scale-factor=1.25"
export _JAVA_AWT_WM_NONREPARENTING=1


bspc config border_width         3
bspc config window_gap           7

bspc config split_ratio          0.44
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config focus_by_distance true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc monitor -d 1 2 3 4 5 6 7 8

bspc rule -a Gnome-terminal state=floating hidden=on sticky=on rectangle=1280x720+0+0 center=on
bspc rule -a Chromium-browser desktop='1'
bspc rule -a Slack desktop='2'
bspc rule -a Atom desktop='3'
bspc rule -a Emacs desktop='3'
bspc rule -a Thunderbird desktop='4'
bspc rule -a TelegramDesktop state=floating sticky=on hidden=on rectangle=1280x720+0+0 center=on

bspc config normal_border_color '#5a253c'
bspc config focused_border_color '#b72350'

sxhkd &
compton --config "$HOME/.config/compton/compton.conf" -b --respect-prop-shadow &
feh --bg-fill ~/.wallpaper/all_night_long.jpg
xautolock -time 5 -locker "i3lock -i -f --color 000000" &
polybar main &
dunst &
chromium-browser &
gnome-terminal --hide-menubar --profile='Tomorrow Night'
slack &
thunderbird &
$HOME/bin/telegram
